"""empty message

Revision ID: 007a9a3cd5a2
Revises: 
Create Date: 2022-07-30 03:39:56.583031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007a9a3cd5a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('cat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('cat_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('cat_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=128), nullable=False),
    sa.Column('material', sa.String(length=128), nullable=True),
    sa.Column('style', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['categories.cat_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('categories')
    # ### end Alembic commands ###
